chore(docs): update README with GitHub Actions setup and add secret checks in CI workflow

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -16,6 +16,31 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Check secrets
+        run: |
+          echo "Checking if required secrets are set..."
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "ERROR: DOCKERHUB_USERNAME secret is not set"
+            exit 1
+          fi
+          if [ -z "${{ secrets.PRODUCTION_SERVER_ADDRESS }}" ]; then
+            echo "ERROR: PRODUCTION_SERVER_ADDRESS secret is not set"
+            exit 1
+          fi
+          if [ -z "${{ secrets.PRODUCTION_SERVER_USERNAME }}" ]; then
+            echo "ERROR: PRODUCTION_SERVER_USERNAME secret is not set"
+            exit 1
+          fi
+          if [ -z "${{ secrets.PRODUCTION_SERVER_PASSWORD }}" ]; then
+            echo "ERROR: PRODUCTION_SERVER_PASSWORD secret is not set"
+            exit 1
+          fi
+          if [ -z "${{ secrets.PRODUCTION_SERVER_PORT }}" ]; then
+            echo "ERROR: PRODUCTION_SERVER_PORT secret is not set"
+            exit 1
+          fi
+          echo "All required secrets are set"
+
       - name: Set up Docker Buildx (for advanced building features)
         uses: docker/setup-buildx-action@v3
 
@@ -47,9 +72,6 @@ jobs:
           docker compose -f compose.yaml build
           docker compose -f compose.yaml push
 
-      - name: Check compose.yaml exists
-        run: ls -l compose.yaml
-
       - name: Create application directory
         uses: appleboy/ssh-action@v1
         with:
@@ -61,14 +83,14 @@ jobs:
             set -e
             mkdir -p ${{ env.APP_PATH }}
 
-      - name: Upload compose.yaml with SCP
+      - name: Upload compose.prod.yaml with SCP
         uses: appleboy/scp-action@v1
         with:
           username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
           password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
           host: ${{ secrets.PRODUCTION_SERVER_ADDRESS }}
           port: ${{ secrets.PRODUCTION_SERVER_PORT }}
-          source: "docker,compose.prod.yaml"
+          source: "compose.prod.yaml"
           target: "${{ env.APP_PATH }}/"
 
       - name: Execute remote SSH commands
@@ -84,6 +106,5 @@ jobs:
           script: |
             set -e
             cd ${{ env.APP_PATH }}
-            # echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env
-            docker compose pull
-            docker compose up -d
+            docker compose -f compose.prod.yaml pull
+            docker compose -f compose.prod.yaml up -d
